### PR TITLE
Modify file handling exceptions to avoid issues when files do not exist with python 2.

### PR DESCRIPTION
**Pull request by vmayoral**

### CODE REVIEW

**Comment by benjmarshall** [comment]
Hi, thanks for opening this and the referenced issue. I'd like to take a closer look because from  a quick glance I think the 'except OSError' already in the try block was intended to catch files which don't exist. I wonder if this may be a Python version issue.

Can you provide a little more info on your system: hlsclt version, python version etc? And steps to reproduce the error detailed in  #9 ?

Thanks.

**Comment by vmayoral** [comment]
Sure thing:
- **hlsclt version**: 1.0.0.a5
- **Python version**: Python 2.7.15rc1

As for reproducing it, simply launching it when `hlsclt build cosim` hasn't been run, breaks for me.

**Comment by benjmarshall** [comment]
I have recreated the issue. It seems to be specific to python 2, where an 'IOError' is being raised instead of an 'OSError' for files not present which is different from the python 3 behaviour.

I believe a better fix is to look specifically for the OSError or IOError exceptions instead of adding a generic catch all which could mask other errors in the future.

I'm going to modify this PR to reflect this and will push some changes with my preferred fix. @vmayoral could you review these, and make sure they fix your previous issue?

**Comment by vmayoral** [comment]
Tested. Works perfectly fine. Thanks!

**Comment by benjmarshall** [comment]
Merged into develop.

**Pull request closed without merging**
